### ISSUE TITLE
Add jobs to menu of tech site

### ISSUE THREAD

**Issue by bart-blommaerts** [ordina-jworks/ordina-jworks.github.io#118]

**Comment by kencoenen** [comment]
Initial layout committed.

Everyone is welcome to contribute. Some todo's by heart:

- [ ] White background for blog posts
- [ ] Footer styling
- [ ] Category overview layout
- [ ] Menu
- [ ] Comments in blogposts aren't rendered
- [ ] Job dynamic layout
- [ ] Add jobs
- [ ] CSS cleanup and SASS/LESS usage
- [x] All blog images same size

**Comment by kencoenen** [comment]
SASS migration is finished. For people that want to contribute, I've written a short intro on SASS and Jekyll in `README.md` of the `feature/jobboard` branch.
