### ISSUE TITLE
Tag overview page doesn't show all posts

### ISSUE THREAD

**Issue by kencoenen** [ordina-jworks/ordina-jworks.github.io#121]
When I want to see all posts about Event Sourcing, the page only shows the Lagom post.
https://ordina-jworks.github.io/tags/event-sourcing/

The article https://ordina-jworks.github.io/domain-driven%20design/2016/02/02/A-Decade-Of-DDD-CQRS-And-Event-Sourcing.html also has Event Sourcing as a tag.

**Comment by TYsewyn** [comment]
The article you mentioned above has the tag 'Event Sourcing', while the other article has the tag 'Event-Sourcing' (mind the dash).
So we actually need to fix the tag in one of the articles.

(or we could fetch all posts for both tags, but that would be a bit more difficult)

**Comment by MrJean** [comment]
#182
