### ISSUE TITLE
Background image could be blurred

### ISSUE THREAD

**Issue by andreasevers** [ordina-jworks/ordina-jworks.github.io#144]
When looking at a blogpost, its image is enlarged.
This makes it look pixelated and imho amateur-hour.

A CSS blur effect could perhaps solve this in a quick and easy way.

<img width="1440" alt="screen shot 2017-01-18 at 15 26 43" src="https://cloud.githubusercontent.com/assets/6663110/22067893/6a12c316-dd93-11e6-9c59-915b6af1d13c.png">

**Comment by kencoenen** [comment]
@andreasevers U vraagt, wij draaien !

**Comment by andreasevers** [comment]
Awesome, thanks!

**Comment by andreasevers** [comment]
The blurred background image slows down the page scrolling and makes it laggy.

**Comment by Turbots** [comment]
still relevant @andreasevers ?

**Comment by andreasevers** [comment]
Yep, performance hit is still there

**Comment by gurtjun** [comment]
Would be cool if we could blur the header image when building the blog. 
https://github.com/koic/blur_image

**Comment by MrJean** [comment]
@gurtjun up for this one with your suggested solution?

**Comment by gurtjun** [comment]
Did a quick check yesterday, [blur_image](https://github.com/koic/blur_image) has a dependency on [MiniMagick](https://github.com/minimagick/minimagick), which is a ruby wrapper for the [ImageMagick](http://imagemagick.org/script/index.php) command line. According to the documentation you have to install ImageMagick before using the command line. Not sure if this is possible?

Tried it on my laptop, but no luck yet.

**Comment by gurtjun** [comment]
Got it working locally. I'll have to check with @Turbots if it's possible to resolve the dependencies like the [blur_image](https://github.com/koic/blur_image/blob/master/.travis.yml#L2)'s `.travis.yml` does.

**Comment by gurtjun** [comment]
All required packages are in this [pre-installed list of packages from codeship](https://documentation.codeship.com/basic/builds-and-configuration/packages/#full-list-of-installed-packages). Not sure why commit 57f547ec4d8a953f40a5675a78b782b28104c6e6 is failing, since I don't have access to Codeship.

**Comment by yannickdeturck** [comment]
Seems like there's an issue with the blur plugin:
```
Destination: dist
Incremental build: disabled. Enable with --incremental
Generating... 
Enriching posts with link to authors
Enriching authors with link to posts
Blur posts background images
jekyll 3.7.2 | Error:  No such file or directory @ rb_sysopen - _site/img/springio.jpg
```

**Comment by gurtjun** [comment]
Hmm, directory structure must be different when building on Codeship?

I installed ImageMagick locally with brew and the blog builds.
`brew install imagemagick`

Op 17 feb. 2018 om 20:53 heeft Yannick De Turck <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Seems like there's an issue with the blur plugin:

Destination: dist
Incremental build: disabled. Enable with --incremental
Generating...
Enriching posts with link to authors
Enriching authors with link to posts
Blur posts background images
jekyll 3.7.2 | Error:  No such file or directory @ rb_sysopen - _site/img/springio.jpg

**Comment by gurtjun** [comment]
Woops,  now some other pages don't have a background-image because they are looking for a `_header` image file.
- job detail
- launch your carreer
- kickstarter programme
- accelerator programme
- constact us

**Comment by yannickdeturck** [comment]
Maybe the grey gradient can also be a bit less darker? Can only faintly see the images now. :-)

**Comment by gurtjun** [comment]
I agree, this can be done by incrementing the percentage here: https://github.com/ordina-jworks/ordina-jworks.github.io/blob/a05744a7fffcb5922e27d724e3ca3d9963492e49/_plugins/header_image_creator.rb#L10

**Comment by Turbots** [comment]
issue has been fixed a while back, thanks @gurtjun !

**Comment by andreasevers** [comment]
Thanks @gurtjun for fixing the performance issue!
Reopening for the flickering orange overlay on loading the page.

**Comment by gurtjun** [comment]
Orange flickering is removed in 8ef993c. Gradient is also a bit less darker.
