### ISSUE TITLE
Comments do not load on website

### ISSUE THREAD

**Issue by MrJean** [ordina-jworks/ordina-jworks.github.io#152]

**Comment by Turbots** [comment]
@TYsewyn same problem as #147 ?

**Comment by TYsewyn** [comment]
Nee, blijkbaar wordt het disqus script niet meer geladen omdat dat niet meer in de footer zit?
Waarschijnlijk bij de rewrite ergens per ongeluk verwijderd @kencoenen?

**Comment by kencoenen** [comment]
Zou kunnen @TYsewyn
