### ISSUE TITLE
Pagination doesn't show current page.

### ISSUE THREAD

**Issue by bart-blommaerts** [ordina-jworks/ordina-jworks.github.io#156]
Nice to have, some kind of highlight to display the page you're currently on.

![image](https://cloud.githubusercontent.com/assets/3988458/22888889/906f8264-f207-11e6-9740-49e23ba490fe.png)

**Comment by MrJean** [comment]
#180

**Comment by MrJean** [comment]
<img width="274" alt="screen shot 2017-04-05 at 14 53 33" src="https://cloud.githubusercontent.com/assets/1266135/24706364/b1e966c8-1a0f-11e7-87a6-d3a129057a07.png">
