### ISSUE TITLE
TypeScript highlights not supported

### ISSUE THREAD

**Issue by KevinVHoutte** [ordina-jworks/ordina-jworks.github.io#17]

**Comment by TYsewyn** [comment]
Awaiting [Rouge PR](https://github.com/jneen/rouge/pull/400)

**Comment by KevinDaHub** [comment]
For a temporary solution: CoffeeScript does not hightlight the ":"

**Comment by TYsewyn** [comment]
Awaiting [Jekyll issue #5774](https://github.com/jekyll/jekyll/issues/5774)

**Comment by TYsewyn** [comment]
Awaiting [Jekyll release 3.6.0](https://github.com/jekyll/jekyll/milestone/57)

**Comment by yannickdeturck** [comment]
Seems to have been released by now: https://jekyllrb.com/news/2017/09/21/jekyll-3-6-0-released/.
