### ISSUE TITLE
Sharing the Tech Blog or jobs page on Social Media should use the JWorks logo

### ISSUE THREAD

**Issue by yannickdeturck** [ordina-jworks/ordina-jworks.github.io#204]
At the moment when sharing the Tech Blog or jobs page on Social Media such as LinkedIn, the image that's being displayed is either one of the latest blogpost images or an image of one of the job positions. It would be better to have it use the JWorks logo imo.

**Comment by bart-blommaerts** [comment]
Should it? Every share might be looking the same and less interesting?
Authors should pay attention to them .. Or maybe add a "image for sharing"-section (cfr. Wordpress)

**Comment by yannickdeturck** [comment]
I'm mainly talking about the landing page of the Tech Blog and the general page of the job positions.
For example if you were to share our Tech blog (https://ordina-jworks.github.io), it shows up as:
<img width="547" alt="screen shot 2017-06-16 at 07 26 19" src="https://user-images.githubusercontent.com/1644089/27213263-053e007a-5266-11e7-9504-8a0dc9d0c810.png">

As for the job positions overview page:
<img width="545" alt="screen shot 2017-06-16 at 07 33 32" src="https://user-images.githubusercontent.com/1644089/27213288-2ad618f4-5266-11e7-9bf2-70c7cc182acf.png">

For these two cases I think it should show our JWorks logo.
For individual blogposts or job positions it's alright to use the image from the post/job position, but when sharing general pages, I think we want to promote JWorks in first instance.

**Comment by bart-blommaerts** [comment]
Agreed!

**Comment by gurtjun** [comment]
Works on Twitter and Facebook, not on Linkedin.

According to [this article](https://woorkup.com/linkedin-cache/) the "old" og:image meta tag is cached by Linkedin. The next time we want to share an article/page we should add a query string `?1` to the URL. This will trick Linkedin and remove the cached image.

Tech blog: https://ordina-jworks.github.io/?1
Jobs: https://ordina-jworks.github.io/jobs/?1

Once done by someone, we can remove the query string and use the original URL.

**Comment by yannickdeturck** [comment]
Interesting, so it's purely something related to LinkedIn's caching.
I've noticed that the JWorks shield image doesn't seem to fit well when the urls are shared on LinkedIn but we can track this in a new issue so that we can close this one.
