### ISSUE TITLE
Rss feed not working

### ISSUE THREAD

**Issue by wonnekeysers** [ordina-jworks/ordina-jworks.github.io#231]
Only 10 blogposts are showing up in https://ordina-jworks.github.io/feed.xml

**Comment by Turbots** [comment]
RSS feeds don't work like that, they usually only show X amount of items, it's the job of the RSS reader to store the older ones and update every X minutes/hours/days.

More information https://stackoverflow.com/questions/576552/how-do-i-fetch-all-old-items-on-an-rss-feed

But it is true that our RSS feed is not updating automatically
