### ISSUE TITLE
Search box and menu box have different heights

### ISSUE THREAD

**Issue by beele** [ordina-jworks/ordina-jworks.github.io#244]
The search box and the menu box have different heights, should be the same height for a better visual experience. See screenshot below:

![screen shot 2017-07-14 at 09 50 05](https://user-images.githubusercontent.com/2178606/28203777-640aed18-687b-11e7-8112-49d92821cc52.png)

**Comment by MrJean** [comment]
#245 @beele

**Comment by Turbots** [comment]
Fixed in #245
