### ISSUE TITLE
Reshape Dev Ops Engineer to Cloud Automation Engineer

### ISSUE THREAD

**Issue by kencoenen** [ordina-jworks/ordina-jworks.github.io#248]
http://ordina-jworks.github.io/jobs/dev-ops/ should be evaluated. Rename it to Cloud Automation Engineer.

Feedback from Marketing is that there are too many bullets with what the candidate should know. This frightens people. When it's done, inform Marketing and more specifically Sara that the tech blog contains the new version and that they can copy it to the new Ordina Job site.

**Comment by basmoorkens** [comment]
after reading the current description it looks more like the google SRE job description. If we are really looking for just a cloud automation profile I think some bullets should be dropped from the description

**Comment by kencoenen** [comment]
Thanks for your effort @KevinVHoutte !
