### ISSUE TITLE
Talk & speaker description link is deprecated

### ISSUE THREAD

**Issue by KevinDaHub** [ordina-jworks/ordina-jworks.github.io#28]
Here under title Master Spring Boot auto-configuration:

http://ordina-jworks.github.io/spring/2015/05/08/SpringIO15-Autoconfig.html

**Comment by bart-blommaerts** [comment]
Seems to work? @KevinDaHub

**Comment by KevinDaHub** [comment]
This is the link: http://www.springio.net/master-spring-boot-auto-configuration/
It has a valid redirect but the component is not found
<img width="1907" alt="screen shot 2016-08-26 at 08 08 45" src="https://cloud.githubusercontent.com/assets/3090371/17995721/5c734a6a-6b64-11e6-8837-dbe444e5f618.png">
