### ISSUE TITLE
Improve tags search

### ISSUE THREAD

**Issue by gurtjun** [ordina-jworks/ordina-jworks.github.io#282]
There are some duplicates in the **Tags** section (e.g. _typescript_, _Typescript_ and _TypeScript_). They all link to the same url (https://ordina-jworks.github.io/tags/typescript/).
When navigating to this url the number of posts for the typescript tag are incorrect. This is due to the fact that the tag page generator does not take uppercases into account. 

I think it would be better if we only had one unique value for each tag. 
We could filter them out **or** rename them all with the same value (the regex `tags: \[.*typescript.*\]` can be used to find them in IntelliJ).

We also should improve the tag page generator to take uppercases into account. Anyone who disagrees with me?

A few examples: 
- _AngularJS_, _angularjs_
- _typescript_, _Typescript_, _TypeScript_
- _Microservices_, _microservices_
- _Internet of Things_, _Internet Of Things_

**Comment by yannickdeturck** [comment]
Nice find, I completely agree! We should clean up the tags
Ideally tags should be mapped to lowercase imo.

**Comment by gurtjun** [comment]
Cool, I already have a local solution for this. Will push it tonight.
Is it ok if all tags are displayed in lowercase?

**Comment by yannickdeturck** [comment]
Awesome!
