### ISSUE TITLE
Image from JWorks Tech Blog urls being shared on LinkedIn results has incorrect size

### ISSUE THREAD

**Issue by yannickdeturck** [ordina-jworks/ordina-jworks.github.io#285]
When sharing a url from the JWorks Tech Blog on LinkedIn the image that gets displayed doesn't exactly fit. 

<img width="538" alt="screen shot 2017-10-26 at 00 00 38" src="https://user-images.githubusercontent.com/1644089/32025558-fc132d62-b9e0-11e7-8651-30d28c8e85a4.png">

Note that in order to test this, the LinkedIn cache should be bypassed by appending a query string to the end of the url as @gurtjun has remarked in #204. 

For example: https://ordina-jworks.github.io/?1

**Comment by gurtjun** [comment]
LinkedIn already linked a badly scaled image to https://ordina-jworks.github.io/?1.

To make sure we get the correct image, use this URL: https://ordina-jworks.github.io/?666 😈

**Comment by yannickdeturck** [comment]
Alright, thanks @gurtjun! 
Closing this issue as LinkedIn's cache will be updated as soon as we've done the trick at least once.
