### ISSUE TITLE
Table of content claps open randomly on mobile

### ISSUE THREAD

**Issue by KevinVHoutte** [ordina-jworks/ordina-jworks.github.io#292]
https://ordina-jworks.github.io/conference/2017/11/15/JavaDay-Ukraine-2017.html

**Comment by yannickdeturck** [comment]
Also on https://ordina-jworks.github.io/spring/2017/07/11/SpringIO17-Summary.html.
Seems to be only when you scroll up on any mobile device that it pops open for no reason.

**Comment by MrJean** [comment]
Issue #345

**Comment by MrJean** [comment]
@yannickdeturck This can be closed?

**Comment by yannickdeturck** [comment]
@MrJean Yes! Looking good. The menu no longer pops open when scrolling.
