### ISSUE TITLE
ToC header overlaps with ToC close button

### ISSUE THREAD

**Issue by Deryaa** [ordina-jworks/ordina-jworks.github.io#296]
<img width="257" alt="screen shot 2017-12-04 at 23 48 25" src="https://user-images.githubusercontent.com/493268/33580477-ac2b5e5a-d94d-11e7-8360-d53a7f37f347.png">

**Comment by Deryaa** [comment]
@MrJean Was dit al geweten? Heb maar een issue geopend just in case. :)

**Comment by MrJean** [comment]
@Deryaa thanks! Nog niet van op de hoogte

**Comment by MrJean** [comment]
Cannot replicate.
