### ISSUE TITLE
Images of Spring IO 2015 blogposts don't work anymore

### ISSUE THREAD

**Issue by andreasevers** [ordina-jworks/ordina-jworks.github.io#325]
They link back to the old ordina.be website (which is gone). New images should be included instead.

**Comment by gurtjun** [comment]
Apparently there are more blogposts with this issue (images and URLs). I will check them all and fix the images/links where possible.

Blogposts with links to the old ordina.be website:
- [Applying software patterns to microservices](https://ordina-jworks.github.io/microservices/2015/10/13/MicroservicesPatterns.html)
- ["Bootiful" Microservices in CloudFoundry & One on One with Josh Long](https://ordina-jworks.github.io/spring/2015/05/08/SpringIO15-Microservices.html)
- [JOIN 2015 from a developer''s perspective](https://ordina-jworks.github.io/join/2015/09/15/JOIN2015.html)
- [JOIN 2016](https://ordina-jworks.github.io/conference/2016/09/27/JOIN-2016.html)
- [Kickstarter Trajectory 2017](https://ordina-jworks.github.io/kickstarters/2017/10/05/Kickstarter-Trajectory-2017.html)
- [Master Spring Boot auto-configuration](https://ordina-jworks.github.io/spring/2015/05/08/SpringIO15-Autoconfig.html)
- [A production Spring reference application & One on One talk with Brian Clozel](https://ordina-jworks.github.io/spring/2015/05/08/SpringIO15-Sagan.html)
- [Spring I/O 2015 Barcelona](https://ordina-jworks.github.io/spring/2015/05/09/SpringIO15-General.html)
- [SpringOne Platform](https://ordina-jworks.github.io/conference/2016/08/09/s1p.html)
- [A web of trusted commits](https://ordina-jworks.github.io/security/2016/07/25/Web-of-trusted-commits.html)

**Comment by gurtjun** [comment]
@kencoenen Do you have any idea which images you used in your [blogpost about JAX London 2015](https://ordina-jworks.github.io/microservices/2015/10/13/MicroservicesPatterns.html)? Can I pick a random image for 'Microservices patterns' and 'Gartner Hype Cycle'?

**Comment by yannickdeturck** [comment]
Awesome, @gurtjun ! 💪🏼
