### ISSUE TITLE
Remove Maarten from Launch Your Career

### ISSUE THREAD

**Issue by yannickdeturck** [ordina-jworks/ordina-jworks.github.io#358]
Maarten is still displayed as RM under the Launch Your Career Programmes.

**Comment by inesvanstappen** [comment]
Does he also have to be removed from Kickstarter, Contact and Accelerator page?

**Comment by yannickdeturck** [comment]
Yes, so both from the two programmes:
- https://ordina-jworks.github.io/launch-your-career/kickstarter-programme
- https://ordina-jworks.github.io/launch-your-career/accelerator-programme

And the contact page:
- https://ordina-jworks.github.io/contact/

**Comment by inesvanstappen** [comment]
Pull Request #365

**Comment by yannickdeturck** [comment]
Fixed in #365.
