### ISSUE TITLE
Add Stephanie Loyens to contacts

### ISSUE THREAD

**Issue by anjavanacker** [ordina-jworks/ordina-jworks.github.io#373]
Stephanie Loyens
Resource Manager
Stephanie.loyens@ordina.be
0496/53.47.05

**Comment by yannickdeturck** [comment]
Tracked in [feature/add-stephanie-loyens](https://github.com/ordina-jworks/ordina-jworks.github.io/tree/feature/add-stephanie-loyens).
Just need a photo.
