### ISSUE TITLE
Show loading bar or spinner when using search functionality

### ISSUE THREAD

**Issue by jmeys** [ordina-jworks/ordina-jworks.github.io#379]
When searching through the articles on the blog, the user is presented with a new - empty - page while the content is still loading. This makes it look like there were no search results for approximately 5 seconds.

**Comment by jmeys** [comment]
Also: all navigation on the page is un-clickable while the search content is loading

**Comment by yannickdeturck** [comment]
We could display a modal spinner to make it more clear that the page is loading.

**Comment by yannickdeturck** [comment]
Fixed in #438 by @gvdp.
