### ISSUE TITLE
"Creating header images for posts" is slow

### ISSUE THREAD

**Issue by miva2** [ordina-jworks/ordina-jworks.github.io#387]
When building "Creating header images for posts" takes a really long time. Usually it takes around 22 seconds to finish building for me. This is annoying when checking small fixes and kind of disrupts the flow sometimes.

Would be nice if we could skip this step during development or choose to only build a single post.

**Comment by gurtjun** [comment]
Not sure if it's possible to skip this during development (not a Jekyll expert 🤓).  

As a workaround I implemented a check if the `_header` file already exists and added `keep_files` for `img` directory to the configuration in dddcf9c. 
As described [here](https://jekyllrb.com/docs/configuration/options/), this will not remove the generated files in the `img` directory on rebuild.

A clean build takes 26 seconds, rebuild only 13 seconds (less than a second for blurring images). Seems that "Enriching authors with links to posts" is also pretty slow.
