### ISSUE TITLE
Optimize space usage Categories

### ISSUE THREAD

**Issue by miva2** [ordina-jworks/ordina-jworks.github.io#393]
On the bottom of the frontpage there is a list with categories.
It's too long and looks stupid.

I suggest either:
- make multiple columns of categories
- Make it smaller like click to open the list or something

Or something better.

Screenshot of current list of Categories. Not everything fits in one screen. Using macbook.
<img width="1440" alt="screen shot 2018-06-28 at 13 31 05" src="https://user-images.githubusercontent.com/7113409/42032167-070d489c-7ad9-11e8-9f6f-19eba57e86fb.png">

**Comment by yannickdeturck** [comment]
Fixed in #437.
