### ISSUE TITLE
Too many tags fills whole screen

### ISSUE THREAD

**Issue by miva2** [ordina-jworks/ordina-jworks.github.io#394]
There are many tags by now.
When scrolling down the homepage we encounter a large cloud of tags (after scrolling past the big list of categories). I think it is best we condense this so visitors have an easier time finding contact information in the footer.

I suggest either:
- Show random 5 or 6 tags on 1 line
- Show tags on click
Or something better.

Current screenshot of Tags.
<img width="1440" alt="screen shot 2018-06-28 at 13 31 27" src="https://user-images.githubusercontent.com/7113409/42032288-6517649a-7ad9-11e8-8740-e673cff1cd00.png">

**Comment by yannickdeturck** [comment]
Styling fixed in #437.
New issue was created for doing a cleanup in #447.
