### ISSUE TITLE
Subscribe functionality

### ISSUE THREAD

**Issue by andreasevers** [ordina-jworks/ordina-jworks.github.io#400]
I'd like to be notified preferably by mail when a new blogpost has been posted.
Using the github watch feature is too verbose since it includes all issues and features/bugfixes.

**Comment by svenbovens** [comment]
Isn't the rss feed sufficient for this? https://ordina-jworks.github.io/feed.xml
If you want it in your mail, I imagine you can use something like https://blogtrottr.com/

**Comment by andreasevers** [comment]
This is fine, but it's not just me who could benefit from this.
I do think the majority of visitors would prefer the ability to simply subscribe to an email notification using a simple form on the website.

**Comment by KevinVHoutte** [comment]
This is on the roadmap for next year to integrate with our tools more
smoothly.

Op za 1 dec. 2018 om 19:01 schreef Andreas Evers <notifications@github.com>:
