### ISSUE TITLE
JOIN

### ISSUE THREAD

**Issue by JMesens** [ordina-jworks/ordina-jworks.github.io#406]
When searching for join Ordina, you will find the category page of join. And it only contains join 2015 and that link seems broken. Would be nice that all join blogposts where grouped in that category and worked.

**Comment by TimDG** [comment]
The URL for that blog post is https://ordina-jworks.github.io/**join**/2015/09/15/JOIN2015.html which clashed with the JOIN subsite on https://ordina-jworks.github.io/join/
