### ISSUE TITLE
Learn more link

### ISSUE THREAD

**Issue by inesvanstappen** [ordina-jworks/ordina-jworks.github.io#407]
Learn more link on contact page leads to a link for the eu unit.

Steps:
Go to https://ordina-jworks.github.io/contact/
Click on learn more in text "about ordina jworks"
You will be redirected to https://www.ordina.be/en/job/java-application-developer/ (for eu unit) instead of https://www.ordina.be/en/job/java-developer/ (for jworks unit)

**Comment by yannickdeturck** [comment]
Going to have it link to https://www.ordina.be/en/competences/java/ instead.
