### ISSUE TITLE
Font size for quotes too small

### ISSUE THREAD

**Issue by yannickdeturck** [ordina-jworks/ordina-jworks.github.io#41]
In comparison with regular text it seems like the font size for quotes is too small.

**Comment by yannickdeturck** [comment]
Fixed in f24c3ee.

**Comment by andreasevers** [comment]
Is the quote supposed to be italic **and** bold?

Perhaps better not to have it bold as well?

**Comment by MrJean** [comment]
@andreasevers Where do you find a bold and italic quote?

**Comment by yannickdeturck** [comment]
Should only be italic unless you manually used bold styling such as here:
<img width="832" alt="screen shot 2016-04-26 at 10 48 12" src="https://cloud.githubusercontent.com/assets/1644089/14812215/7da61c1c-0b9c-11e6-997d-f8b105bd22a2.png">

**Comment by MrJean** [comment]
@yannickdeturck @andreasevers Indeed, has nothing to do with styling. I'll close this one.
@andreasevers Please create ticket to solve the text formatting in the blog post.
