### ISSUE TITLE
ERROR `/img/backgrounds/ordina_header.png' not found.

### ISSUE THREAD

**Issue by yannickdeturck** [ordina-jworks/ordina-jworks.github.io#410]
Error is encountered when navigating to http://localhost:4000/contact/.
`ordina.png` is a valid image but due to the blurring workflow with imagemagick it expects to find a blurred version called `ordina_header.png`. This blurred image does not exist because as it currently stand only a blurred version is created for the posts.

See: 
- https://github.com/ordina-jworks/ordina-jworks.github.io/blob/source/js/main.js#L316
- https://github.com/ordina-jworks/ordina-jworks.github.io/blob/source/_plugins/header_image_creator.rb
-  https://github.com/ordina-jworks/ordina-jworks.github.io/blob/source/_plugins/hooks/site/post_write/header_image.rb

Either we should also generate a blurred version of the `ordina.png` file or we should use the original file as background image.

**Comment by gurtjun** [comment]
Same for the [Launch Your Career](https://ordina-jworks.github.io/launch-your-career/) page. 
Added the images for now but would be better to refactor the blurring workflow.
