### ISSUE TITLE
Clean up tags

### ISSUE THREAD

**Issue by yannickdeturck** [ordina-jworks/ordina-jworks.github.io#447]
Certain tags should be merged.
"Useless" tags should be removed.

**Comment by DenMette** [comment]
@yannickdeturck how do you see this?

**Comment by DenMette** [comment]
A small graphic to show the above list 
![image](https://user-images.githubusercontent.com/849003/71920368-d6f54b80-3186-11ea-981e-6974944d38da.png)

**Comment by yannickdeturck** [comment]
> @yannickdeturck how do you see this?

Our tag cloud is rather huge right now. Would be nice if we could clean it up a bit.
Would make sense to go through all tags that are used once or twice and to see if they are absolutely necessary such as the tag "Apple" and "Pi".

Also, as it currently stands the counting of the tags appears to be case sensitive, resulting in double tags e.g. "Cloud" vs "cloud".
