### ISSUE TITLE
Clean up categories

### ISSUE THREAD

**Issue by yannickdeturck** [ordina-jworks/ordina-jworks.github.io#448]
Angular categories should be merged.

**Note: if we alter posts' categories this means we'll alter the url behind the posts. We need to preserve the old url next to the new url.**

**Comment by gurtjun** [comment]
Should we also merge the conferences (JOIN-event, Devoxx, JAX London)?

**Comment by yannickdeturck** [comment]
> Should we also merge the conferences (JOIN-event, Devoxx, JAX London)?

Sounds good. We can merge them all under Conference.

**Comment by gurtjun** [comment]
> > Should we also merge the conferences (JOIN-event, Devoxx, JAX London)?
> 
> Sounds good. We can merge them all under Conference.

Should be fixed in #449
