### ISSUE TITLE
Add Robbe as point of contact

### ISSUE THREAD

**Issue by DenMette** [ordina-jworks/ordina-jworks.github.io#475]
Shouldn't we add Robbe as point of contact next to Anja?

**Comment by yannickdeturck** [comment]
Yes! :)

**Comment by DenMette** [comment]
Can someone provide a picture of Robbe?

**Comment by Nxtra** [comment]
I asked Robbe if he has this picture in higher resolution so we can cut him out. https://www.ordina.be/wp-content/uploads/sites/9/2018/06/Robbe-Struys-200x200.jpg

**Comment by Nxtra** [comment]
Added Robbe's picture in the img/contact folder. Picture has yet to be edited to make it conform with the others.

**Comment by DenMette** [comment]
Robbe is already added as contact
