### ISSUE TITLE
People who left JWorks

### ISSUE THREAD

**Issue by SmetsSander** [ordina-jworks/ordina-jworks.github.io#486]
Remove author or change author description for people who left JWorks?

**Comment by yannickdeturck** [comment]
Ex-colleagues aren't shown on the "About us" page and an "Alumnus" badge is shown on top of their picture on their profile page. Or are you referring to some specific page?

**Comment by SmetsSander** [comment]
Jef and Michiel Willems are still shown in the "About us" page.

**Comment by yannickdeturck** [comment]
Good point, needs to be updated!
