### ISSUE TITLE
JOIN: Layout issue on mobile

### ISSUE THREAD

**Issue by yannickdeturck** [ordina-jworks/ordina-jworks.github.io#487]
Most likely caused by the link.

![photo_2019-02-15 20 23 32](https://user-images.githubusercontent.com/1644089/52879503-93a18100-315f-11e9-8f38-db62b671b554.jpeg)

**Comment by MrJean** [comment]
@yannickdeturck thanks for reporting. Issue belongs on JOIN repo. PR open here: https://github.com/ordina-jworks/join/pull/41

**Comment by yannickdeturck** [comment]
Fixed in ordina-jworks/join#41.
