### ISSUE TITLE
Duplicate link in table of contents Spring IO blogpost

### ISSUE THREAD

**Issue by HPacquee** [ordina-jworks/ordina-jworks.github.io#525]
The link for "Building better monoliths - Modulithic Applications with Spring Boot by Oliver Drotbohm" appears in the table of contents twice, in 3rd and in 12th place.

**Comment by yolanv** [comment]
Thank you for telling us!

**Comment by yannickdeturck** [comment]
Solved in #526.
Thanks, Haroun! 👊🏻
