### ISSUE TITLE
title contains ALL previous authors, causing weird social media links

### ISSUE THREAD

**Issue by HPacquee** [ordina-jworks/ordina-jworks.github.io#531]
The generated titles for title, og:title and twitter:title contain the names of ALL previous blog-post authors. Causing some weird side-effects on social media shares. 

Probably something in the 'authors' collection build logic in `_layouts/default.html` 

<img width="555" alt="Screenshot 2019-08-23 at 15 36 41" src="https://user-images.githubusercontent.com/4233379/63596574-d6835c00-c5bb-11e9-9b59-5ad4608a3c24.png">

<img width="1651" alt="Screenshot 2019-08-23 at 15 37 21" src="https://user-images.githubusercontent.com/4233379/63596614-eac75900-c5bb-11e9-8a15-9831a90f2dcb.png">

**Comment by yannickdeturck** [comment]
A disturbance in the force...
We're on it. 🕵🏻‍♂️

**Comment by kencoenen** [comment]
Solved!
