### ISSUE TITLE
Make it possible to see all work provided by an author

### ISSUE THREAD

**Issue by Nxtra** [ordina-jworks/ordina-jworks.github.io#559]
I was just searching for all post of Kevin Van Den Abeele to find mor info about IoT. I couldn't figure out how to do that.
Is this something we can add?

**Comment by yannickdeturck** [comment]
Hey @Nxtra, you can visit the profile page of the author to view all posts published by him: https://ordina-jworks.github.io/author/kevin-van-den-abeele/

Or you can check the tags or categories at the bottom of the page: https://ordina-jworks.github.io/categories/iot/
