### ISSUE TITLE
LinkedIn hyperlink broken

### ISSUE THREAD

**Issue by yolanv** [ordina-jworks/ordina-jworks.github.io#573]
In the footer of our blog, there is a link to Ordina's LinkedIn page. At the moment, this link does not work because the URL is not the correct one.

Need to change it to the correct URL (ordina-belgium - - > ordinabelgium)

**Comment by DenMette** [comment]
Also the Google+ account disappeared.

**Comment by yannickdeturck** [comment]
We can leave the Google+ account out.

**Comment by yannickdeturck** [comment]
Fixed in #582.
