### ISSUE TITLE
Update kustomize blogpost based on Andreas feedback

### ISSUE THREAD

**Issue by pietervincken** [ordina-jworks/ordina-jworks.github.io#607]
Misschien om de blogpost nog duidelijker te maken zoude da eventueel er nog voor kunnen includen
Aja en mocht ge generators en transformers kort toelichten voor het te vermelden zou dat ook verlichtend zijn

Nog een puntje
> #...original yaml...
is met niet echt duidelijk wat dit dan juist was

**Comment by yannickdeturck** [comment]
Fixed in #608.
