### ISSUE TITLE
Code tabs CSS improvements

### ISSUE THREAD

**Issue by jmeys** [ordina-jworks/ordina-jworks.github.io#641]
Fix the font-color when dark mode is enabled.
Maybe round the corners as well, as this conflicts a little with the code block underneath.
![tabs](https://user-images.githubusercontent.com/14360008/98687053-94356e80-2369-11eb-9c0f-9f2182ab018a.png)

The look was based on the Spring docs, where the code block is more squared as well:
![tabs-spring](https://user-images.githubusercontent.com/14360008/98687370-f1c9bb00-2369-11eb-8325-ef51c72861cb.png)

**Comment by DenMette** [comment]
I added a PR for this ;-)
