### ISSUE TITLE
Move away from CodeShip to Github Actions

### ISSUE THREAD

**Issue by DenMette** [ordina-jworks/ordina-jworks.github.io#678]
Is it a good idea to move to Github Actions?

There is a post on jekyll to do this.
https://jekyllrb.com/docs/continuous-integration/github-actions/

**Comment by wouternivelle** [comment]
As of 16/12/2021, Github has automatically added an action for public repo's that use Jekyll.

https://github.blog/changelog/2021-12-16-github-pages-using-github-actions-for-builds-and-deployments-for-public-repositories/

You can also see the action on https://github.com/ordina-jworks/ordina-jworks.github.io/actions/runs/1829719309.
So I guess the issue can be closed and Codeship can be disabled.
