### ISSUE TITLE
Open links default in a new tab?

### ISSUE THREAD

**Issue by bart-blommaerts** [ordina-jworks/ordina-jworks.github.io#79]

**Comment by TYsewyn** [comment]
We can't achieve the result by just setting a config parameter. (for now)
You can, however, use following solution:

`["Go to my link"](https://www.link.to){:target="_blank"}`

**Comment by MrJean** [comment]
I agree with @TYsewyn . You don't want all links to open in a new window.

**Comment by Turbots** [comment]
@TYsewyn workaround is enough for me at the moment

**Comment by bart-blommaerts** [comment]
Ok. Workaround will do.
