### ISSUE TITLE
Fix broken LinkedIn link on all pages. 

### ISSUE THREAD

**Issue by pietervincken** [ordina-jworks/ordina-jworks.github.io#811]

**Comment by DenMette** [comment]
Pieter wat bedoel je hiermee?

**Comment by pietervincken** [comment]
<img width="1523" alt="Screenshot 2023-09-12 at 13 26 56" src="https://github.com/ordina-jworks/ordina-jworks.github.io/assets/4153479/82cd2537-295e-4827-9bff-22ccf88e06ea">

**Comment by DenMette** [comment]
Oke :wink: , niet de share knop naar linked in
